name: 'Create-Tinycheck-IOC-File'
on:
  push:
    branches: ['master']
    paths: ['network.csv', 'sha256.csv', 'certificates.yaml', 'appid.yaml']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build IOC File
      run: |
          pip install -r scripts/requirements.txt
          python scripts/create-indicators-for-tinycheck.py
          python scripts/make_misp_event.py
          python scripts/generate_stix.py
    - name: Commit files  # transfer the json file in the repo
      run: |
        git config --local user.name  ${{ github.actor }}
        git add generated/
        git commit -m "Updating indicators for Tiny Check, MISP and MVT"
    - name: Push changes  # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
